function H = plotBase(params)
    H = gobjects(0);

    % Colors
    gray = [0.5,0.5,0.5];
    copper = [0.72, 0.45, 0.2];

    % Plot permanent magnets
    for i = 1:length(params.permanent.r)
        plotSingleSolenoid( ...
            params.permanent.x(i), ...
            params.permanent.y(i), ...
            params.permanent.z(i), ...
            params.permanent.r(i), ...
            params.permanent.l(i), ...
            gray);
    end

    % Plot solenoids
    for i = 1:length(params.solenoids.r)
        plotSingleSolenoid( ...
            params.solenoids.x(i), ...
            params.solenoids.y(i), ...
            params.solenoids.z(i), ...
            params.solenoids.r(i), ...
            params.solenoids.l(i), ...
            copper);
    end

    % Plot sensors
    scatter3(params.sensors.x,params.sensors.y,params.sensors.z,'red','filled')
end
